package models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.sql.Timestamp;
import java.util.Map;

@DynamoDBTable(tableName="Orders")
public class Order {

    private String _id;
    private Timestamp timestamp;
    private Customer customer;
    private Map<String, Integer> cart;

    public Order(){}

    public Order (String _id, Timestamp timestamp, Customer customer, Map<String, Integer> cart) {
        this.timestamp = timestamp;
        this.customer = customer;
        this.cart = cart;
        this._id = _id;
    }

    @DynamoDBHashKey(attributeName="_id")
    @DynamoDBAutoGeneratedKey
    public String getId() { return _id; }
    public void setId(String _id) { this._id = _id; }

    @DynamoDBAttribute(attributeName = "Timestamp")
    public Timestamp getTimestamp() { return timestamp; }
    public void setTimestamp(Timestamp timestamp) { this.timestamp = timestamp; }

    @DynamoDBAttribute(attributeName = "Customer")
    public Customer getCustomer() { return customer; }
    public void setCustomer(Customer customer) { this.customer = customer; }

    @DynamoDBAttribute(attributeName = "Cart")
    public Map<String, Integer> getCart() { return cart; }
    public void setCart(Map<String, Integer> cart) { this.cart = cart; }
}
