package models;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

@DynamoDBTable(tableName="ProductCatalog")
public class Product {

    private String _id;
    private String name;
    private String category;
    private String description;
    private String features;
    private String language;
    private String genre;
    private String image;       //URI to product image
    private double price;
    private int quantity;

    private static final int DEFAULT_QUANTITY = 1000;


    public Product(){
        this.quantity = DEFAULT_QUANTITY;
    }

    public Product(String _id, String name, String category, String description,
                   String features, String language, String genre, String image, double price) {
        this._id = _id;
        this.name = name;
        this.category = category;
        this.description = description;
        this.features = features;
        this.language = language;
        this.genre = genre;
        this.image = image;
        this.price = price;
        this.quantity = DEFAULT_QUANTITY;
    }

    public Product(String _id, String name, String category, String description,
                   String features, String language, String genre, String image, double price, int quantity) {
        this._id = _id;
        this.name = name;
        this.category = category;
        this.description = description;
        this.features = features;
        this.language = language;
        this.genre = genre;
        this.image = image;
        this.price = price;
        this.quantity = quantity;
    }

    @DynamoDBHashKey(attributeName="_id")
    @DynamoDBAutoGeneratedKey
    public String getId() { return _id; }
    public void setId(String _id) { this._id = _id; }

    @DynamoDBAttribute(attributeName = "Name")
    public String getName() { return name; }
    public void setName(String name) { this.name = name; }

    @DynamoDBAttribute(attributeName = "Category")
    @DynamoDBIndexHashKey(attributeName = "Category", globalSecondaryIndexName = "CategoryIndex")
    public String getCategory() { return category; }
    public void setCategory(String category) { this.category = category; }

    @DynamoDBAttribute(attributeName = "Description")
    public String getDescription() { return description; }
    public void setDescription(String description) { this.description = description; }

    @DynamoDBAttribute(attributeName = "Features")
    public String getFeatures() { return features; }
    public void setFeatures(String features) { this.features = features; }

    @DynamoDBAttribute(attributeName = "Language")
    public String getLanguage() { return language; }
    public void setLanguage(String language) { this.language = language; }

    @DynamoDBAttribute(attributeName = "Genre")
    public String getGenre() { return genre; }
    public void setGenre(String genre) { this.genre = genre; }

    @DynamoDBAttribute(attributeName = "Image")
    public String getImage() { return image; }
    public void setImage(String image) { this.image = image; }

    @DynamoDBRangeKey(attributeName = "Price")
    public double getPrice() { return price; }
    public void setPrice(double price) { this.price = price; }

    @DynamoDBAttribute(attributeName = "Quantity")
    public int getQuantity(){ return quantity; }
    public void setQuantity(int quantity){ this.quantity = quantity; }
}

